name: renderHtml

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
 
    # Setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 14.4.0

    - name: Install modules
      run: npm install

    - name: Run app
      run: node ./renderHtml.js

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'

    - run: cd dist && azcopy_v10 cp "./*" "${{ secrets.DEST_BASE_URL }}${{ secrets.SAS_TOKEN }}" --recursive